Repository OneBitAritcle/oba_data, pull requests merged in 2025-09, with the labels that each got.

#7 [ON-27] 기사 선정 방법론 기술개발문서 작성
  README.md
Labels: 📝 documentation

#8 [ON-51] DB / Table 생성 및 문서 정리
  db_init/db_initialize.sql
Labels: 📝 documentation

#9 [ON-48] linkCrawling 반환 데이터 수정
  airflow/dags/libs/news_article/crawler/linkCrawling.py
Labels: 🔧 fix

#10 [ON-47] 패키지 의존성 관리
  airflow/requirements.txt
  airflow/requirements_guide.md
Labels: 📝 documentation

#14 [ON-13] article_db_handler 함수 구현
  .gitignore
  airflow/dags/libs/news_article/crawler/__pycache__/linkCrawling.cpython-311.pyc
  airflow/dags/libs/news_article/db_update/__pycache__/article_db_handler.cpython-311.pyc
  airflow/dags/libs/news_article/db_update/__pycache__/article_db_handler_recommendated.cpython-311.pyc
  airflow/dags/libs/news_article/db_update/article_db_handler.py
  airflow/requirements.txt
  db_init/db_initialize.sql
  db_init/first_day_insertion.sql
Labels: ✨ feature

#15 [ON-55] DAG 기본 구조 설계 및 스켈레톤 추가
  airflow/dags/news_crawling_to_db_dag.py
  airflow/dags/select_top5_and_save_dag.py
  airflow/requirements.txt
Labels: ✨ feature

#17 [ON-56] 전체 ETL 자동화 Airflow DAG 설계 및 구현
  .gitignore
  airflow/airflow.cfg
  airflow/airflow.db
  airflow/dags/news_crawling_to_db_dag.py
  airflow/dags/select_top5_and_save_dag.py
  airflow/requirements.txt
  airflow/webserver_config.py
Labels: ✨ feature
